[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "ics>=0.7.2",
    "pytz>=2025.2",
    "requests>=2.32.4",
]
